services:
  db:
    image: postgres:15-alpine
    container_name: stratologia_db
    restart: always
    environment:
      POSTGRES_USER: stratologia_user
      POSTGRES_PASSWORD: stratologia_pass
      POSTGRES_DB: stratologia_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: stratologia_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
  mailhog:
    image: mailhog/mailhog:latest
    container_name: stratologia_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  
  api:
    build: . 
    container_name: stratologia_api
    restart: always
    environment:
      - DB_HOST=db 
      - DB_PORT=5432
      - DB_NAME=stratologia_db
      - DB_USER=stratologia_user
      - DB_PASS=stratologia_pass
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - KEYCLOAK_BACKEND_URL=http://keycloak:8080
    ports:
      - "5000:5000"
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: stratologia_jenkins
    restart: always
    user: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/giannos/.docker/desktop/docker.sock
      - /usr/bin/docker:/usr/bin/docker

volumes:
  pgdata:
  keycloak_data:
  jenkins_data: