---
- name: Εγκατάσταση Υποδομής Stratologia στο Kubernetes
  hosts: k8s_cluster
  gather_facts: false

  tasks:
    - name: 1. Deploy PostgreSQL (PVC, Deployment, Service)
      kubernetes.core.k8s:
        state: present
        src: manifests/postgres.yaml
        namespace: default

    - name: 2. Deploy Keycloak
      kubernetes.core.k8s:
        state: present
        src: manifests/keycloak.yaml
        namespace: default

    - name: 3. Deploy Mailhog
      kubernetes.core.k8s:
        state: present
        src: manifests/mailhog.yaml
        namespace: default

    - name: 4. Deploy Stratologia API
      kubernetes.core.k8s:
        state: present
        src: manifests/api.yaml
        namespace: default